//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebAPIDispatcherReq", Namespace="http://schemas.datacontract.org/2004/07/WebAPIDispatcherWS")]
    [System.SerializableAttribute()]
    public partial class WebAPIDispatcherReq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoCampaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HorarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCampania {
            get {
                return this.CodigoCampaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoCampaniaField, value) != true)) {
                    this.CodigoCampaniaField = value;
                    this.RaisePropertyChanged("CodigoCampania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoOrigen {
            get {
                return this.CodigoOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoOrigenField, value) != true)) {
                    this.CodigoOrigenField = value;
                    this.RaisePropertyChanged("CodigoOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Horario {
            get {
                return this.HorarioField;
            }
            set {
                if ((this.HorarioField.Equals(value) != true)) {
                    this.HorarioField = value;
                    this.RaisePropertyChanged("Horario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefonos {
            get {
                return this.TelefonosField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonosField, value) != true)) {
                    this.TelefonosField = value;
                    this.RaisePropertyChanged("Telefonos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto {
            get {
                return this.TextoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoField, value) != true)) {
                    this.TextoField = value;
                    this.RaisePropertyChanged("Texto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebAPIDispatcherRes", Namespace="http://schemas.datacontract.org/2004/07/WebAPIDispatcherWS")]
    [System.SerializableAttribute()]
    public partial class WebAPIDispatcherRes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDLeadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDLead {
            get {
                return this.IDLeadField;
            }
            set {
                if ((this.IDLeadField.Equals(value) != true)) {
                    this.IDLeadField = value;
                    this.RaisePropertyChanged("IDLead");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebAPIDispatcherSVC.IWebAPIDispatcherService")]
    public interface IWebAPIDispatcherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebAPIDispatcherService/RegistrarLlamada", ReplyAction="http://tempuri.org/IWebAPIDispatcherService/RegistrarLlamadaResponse")]
        WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.WebAPIDispatcherRes RegistrarLlamada(WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.WebAPIDispatcherReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebAPIDispatcherService/RegistrarLlamada", ReplyAction="http://tempuri.org/IWebAPIDispatcherService/RegistrarLlamadaResponse")]
        System.Threading.Tasks.Task<WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.WebAPIDispatcherRes> RegistrarLlamadaAsync(WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.WebAPIDispatcherReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebAPIDispatcherService/RegistrarLlamadaPost", ReplyAction="http://tempuri.org/IWebAPIDispatcherService/RegistrarLlamadaPostResponse")]
        WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.WebAPIDispatcherRes RegistrarLlamadaPost(WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.WebAPIDispatcherReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebAPIDispatcherService/RegistrarLlamadaPost", ReplyAction="http://tempuri.org/IWebAPIDispatcherService/RegistrarLlamadaPostResponse")]
        System.Threading.Tasks.Task<WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.WebAPIDispatcherRes> RegistrarLlamadaPostAsync(WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.WebAPIDispatcherReq req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebAPIDispatcherServiceChannel : WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.IWebAPIDispatcherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebAPIDispatcherServiceClient : System.ServiceModel.ClientBase<WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.IWebAPIDispatcherService>, WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.IWebAPIDispatcherService {
        
        public WebAPIDispatcherServiceClient() {
        }
        
        public WebAPIDispatcherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebAPIDispatcherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebAPIDispatcherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebAPIDispatcherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.WebAPIDispatcherRes RegistrarLlamada(WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.WebAPIDispatcherReq req) {
            return base.Channel.RegistrarLlamada(req);
        }
        
        public System.Threading.Tasks.Task<WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.WebAPIDispatcherRes> RegistrarLlamadaAsync(WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.WebAPIDispatcherReq req) {
            return base.Channel.RegistrarLlamadaAsync(req);
        }
        
        public WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.WebAPIDispatcherRes RegistrarLlamadaPost(WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.WebAPIDispatcherReq req) {
            return base.Channel.RegistrarLlamadaPost(req);
        }
        
        public System.Threading.Tasks.Task<WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.WebAPIDispatcherRes> RegistrarLlamadaPostAsync(WebAPIDispatcherClienteWeb.WebAPIDispatcherSVC.WebAPIDispatcherReq req) {
            return base.Channel.RegistrarLlamadaPostAsync(req);
        }
    }
}
