
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Fwk Code Generator.
//     Runtime Version:1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------
        
using System;
using System.Collections.Generic;
using Fwk.Bases;
using System.Xml.Serialization;
using Fwk.Security.BE;
using Fwk.Security.Identity;

namespace Fwk.Security.Identity.ISVC.SearchRulesCategoryByParam
{

    [Serializable]
    public class SearchRulesCategoryByParamReq : Request<SecurityRulesCategoryBE>
    {
        public SearchRulesCategoryByParamReq()
        {
            this.ServiceName = "SearchRulesCategoryByParamService";
        }
    }
   

    [Serializable]
    public class SearchRulesCategoryByParamRes : Response<SecurityRulesCategoryBEList>
    {
    }



    
}
       